if: NOT tag =~ ^ci/
language: java
matrix:
 include:
  - os: linux
    jdk: oraclejdk9
  - os: linux
    jdk: openjdk8
  - os: linux
    jdk: openjdk10
sudo: false
addons:
    apt:
      update: true
before_install:
 - cp .travis.settings.xml $HOME/.m2/settings.xml
 - if [[ "$TRAVIS_OS_NAME" = linux ]]; then sudo apt-get install jshon ; fi
 - mkdir -p $HOME/.script
 - curl -s https://report.ci/annotate.py > $HOME/.script/annotate.py
 - curl -s https://report.ci/upload.py > $HOME/.script/upload.py
 - curl -s https://codecov.io/bash > $HOME/.script/codecov.bash
 - chmod +x $HOME/.script/codecov.bash
 - chmod +x .travisci/*.sh
install:
- "mvn dependency:resolve dependency:resolve-plugins"
- .travisci/getcodacy.sh
script:
- set -o pipefail
- "mvn  -e clean install 2>&1 | tee maven.log"
after_failure:
- set +o pipefail
- rm -rf target/local-repo
- .travisci/reportci.sh
after_success:
- set +o pipefail
- rm -rf target/local-repo
- .travisci/reportci.sh
- "mvn jacoco:report coveralls:report -DrepoToken=${repoToken}"
- .travisci/codecov.sh
- "mvn jacoco:merge -Djacoco.destFile=target/jacoco-aggregate.exe"
- "mvn jacoco:report -Djacoco.dataFile=target/jacoco-aggregate.exe"
- "(java -jar $HOME/.script/codacy-coverage-reporter.jar report -l Java -r target/site/jacoco/jacoco.xml)"
- "$HOME/.script/codecov.bash -Ffull$TRAVIS_OS_NAME$TRAVIS_JDK_VERSION"
- "mvn site"
before_deploy:
- git config --local user.name "powerunitci"
- git config --local user.email "powerunitci@powerunit.ch"
- if [[ "$TRAVIS_TAG" =~ powerunit-extensions-matchers-[0-9].[0-9].[0-9] ]]; then echo "No tag to be created" ; else git tag -m "Create ci tag [ci skip]" -f "ci/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER"; fi
- "mvn org.apache.maven.plugins:maven-changes-plugin:announcement-generate"
- export RELEASE_NOTES=$(jshon -s "$(cat target/announcement/announcement.vm)")
deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: false
    github-token: $GITHUB_TOKEN
    local-dir: target/site
    on:
      branch: master
      condition: $TRAVIS_JDK_VERSION = openjdk8
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: target/*.jar
    skip_cleanup: true
    prerelease: true
    draft: false
    body: "$RELEASE_NOTES"
    on:
      branch: master
      tags: false
      condition: $TRAVIS_JDK_VERSION = openjdk8
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: target/*.jar
    skip_cleanup: true
    prerelease: false
    draft: false
    body: "$RELEASE_NOTES"
    on:
      tags: true
      condition: $TRAVIS_JDK_VERSION = openjdk8 && "$TRAVIS_TAG" =~ powerunit-extensions-matchers-[0-9].[0-9].[0-9]
